### ISSUE TITLE
Source for generate-oidc-keys-json-linux ?

### ISSUE THREAD

**Issue by rrichardson** [alex-ferener/aws-irsa-kops#1]
Thanks for charting this course so that others may benefit in a big way.  I appreciate it. 

Where can I find the source for `generate-oidc-keys-json-linux`  I would just like to know what it's doing. 

Thanks. 

**Edit** 

`objdump` on the binary pointed me to `square/go-jose` which has hit me with a very large clue stick.

**Comment by alex-ferener** [comment]
Hello,

The source is https://github.com/aws/amazon-eks-pod-identity-webhook/blob/master/hack/self-hosted/main.go

Instead of using the binaries from this repo, you can install golang and run:

```go run main.go -key $PKCS_KEY | jq '.keys += [.keys[0]] | .keys[1].kid = ""' > $OIDC_DIR/keys.json```
